---
- name: install keepalived
  include_role:
    name: packages
  vars:
    packages_list:
      - keepalived

- name: configure keepalived (templated)
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes
  notify: restart keepalived
  when: keepalived_config_templated|bool

- name: configure keepalived (freeform)
  copy:
    content: "{{ keepalived_config }}"
    dest: /etc/keepalived/keepalived.conf
    backup: yes
  notify: restart keepalived
  when: not keepalived_config_templated|bool

- name: apply overrides
  block:
    - name: create keepalived override dir
      file:
        path: /etc/systemd/system/keepalived.service.d
        state: directory
    - copy:
        dest: /etc/systemd/system/keepalived.service.d/override.conf
        content: "{{ keepalived_systemd_overrides }}"
      notify:
        - restart keepalived
      register: keepalived_overrides
    - systemd:
        daemon_reload: true
      when: keepalived_overrides.changed
  when: keepalived_systemd_overrides != ''

- name: apply overrides
  block:
    - name: create keepalived override dir
      file:
        path: /etc/systemd/system/keepalived.service.d
        state: directory
    - copy:
        dest: /etc/systemd/system/keepalived.service.d/override.conf
        content: "{{ keepalived_systemd_overrides }}"
      notify:
        - restart keepalived
      register: keepalived_overrides
    - systemd:
        daemon_reload: true
      when: keepalived_overrides.changed
  when: keepalived_systemd_overrides != ''

- name: start keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes


