---
- name: add prereqs
  include_role:
    name: packages
  vars:
    packages_list:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
  register: add_docker_apt_key

- name: prepare repo line
  shell: |
    echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  register: repo_line
  changed_when: false

- name: add docker repo
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      {{ repo_line.stdout }}
  register: add_docker_repo

- name: apt update
  apt:
    update_cache: true
  when: add_docker_apt_key.changed or add_docker_repo.changed

- name: add docker packages
  include_role:
    name: packages
  vars:
    packages_list:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin 
