---
- include_role:
    name: packages
  vars:
    packages_list: 
      - "{{ 'ceph-mgr'+ceph_package_version|default('') }}"

- include_role:
    name: shellscript
  vars:
    script: |
      if [[ -d /var/lib/ceph/mgr/{{ ceph_cluster_name }}-`hostname` ]]
      then
        echo "There is an existing MGR on this host, skipping deploy."
        ret=0
      else
        mkdir /var/lib/ceph/mgr/{{ ceph_cluster_name }}-`hostname`
        ceph auth get-or-create mgr.`hostname -s` mon 'allow profile mgr' osd 'allow *' mds 'allow *' -o /var/lib/ceph/mgr/{{ ceph_cluster_name }}-`hostname`/keyring
        chown -R ceph:ceph /var/lib/ceph/mgr/{{ ceph_cluster_name }}-`hostname`
        ret=1
      fi
      systemctl enable ceph-mgr.target
      systemctl enable ceph-mgr@`hostname`
      systemctl start ceph-mgr@`hostname`
      exit $ret
