---
- include_role:
    name: packages

- include_role:
    name: keepalived
  when: haproxy_keepalived

- name: certs dir
  file:
    path: /etc/ssl/private
    state: directory
    owner: root
    group: root 

## Define any certs in haproxy_certs var (hopefully encrypted) 
## eg. This will create /etc/ssl/private/my_cert.pem
## and /etc/ssl/private/my_cert.key (optional)
##  haproxy_certs:
##    - name: my_cert
##      pem: |
##        ---begin certificate---
##        blahblahblahblahblahblahblah 
##        ---end certificate---
##      key: |
##        ---begin private key---
- include_role:
    name: ssl
  vars:
    ssl_certs: "{{ haproxy_certs }}"
    ssl_webservers: ['haproxy']

- template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart haproxy
  tags: cfg

- name: ensure dir
  file:
    path: /var/log/haproxy
    state: directory
    follow: yes 

- name: configure rsyslog specials
  copy:
    content: |
      $AddUnixListenSocket /var/lib/haproxy/log
      local2.*  -/var/log/haproxy/haproxy.log
      & stop
    dest: /etc/rsyslog.d/a_haproxy.conf
    mode: 0644
    owner: root
    group: root
  notify: restart rsyslog

- name: logrotate conf
  copy:
    src: haproxy_logrotate
    dest: /etc/logrotate.d/haproxy_logr


#- name: keep logs 90 days
#  lineinfile:
#    path: /etc/logrotate.d/haproxy
#    regexp: '^(.*) rotate'
#    line: '\1 rotate 180'
#    backrefs: yes
